version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: cakestore-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cakestore
      POSTGRES_USER: cakestore
      POSTGRES_PASSWORD: cakestore_dev
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
